packages:
  - "apps/*"
  - "packages/*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.16
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp

onlyBuiltDependencies:
  - workerd
overrides:
  vite: "catalog:"
  vitest: "catalog:"

patchedDependencies:
  drizzle-orm: patches/drizzle-orm.patch
  effect@4.0.0-beta.42: patches/effect@4.0.0-beta.42.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
