version: "0.5"

processes:
  shared:
    command: vp run shared#dev
    ready_log_line: Rebuilt in

  sql-sqlite-wasm:
    command: vp run sql-sqlite-wasm#dev
    ready_log_line: Rebuilt in

  extension:
    command: vp run extension#dev
    disabled: true
    depends_on:
      shared:
        condition: process_log_ready

  web:
    command: vp run web#dev
    depends_on:
      shared:
        condition: process_log_ready
      sql-sqlite-wasm:
        condition: process_log_ready
