// Generated by Wrangler by running `wrangler types` (hash: 2905fd8e181cd2f4083a615fa51f1913)
// Runtime types generated with workerd@1.20250405.0 2025-04-07
declare namespace Cloudflare {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
  interface Env {}
}
interface Env extends Cloudflare.Env {}
