// Generated by Wrangler by running `wrangler types` (hash: 751a7ef0204e37564547937fa13c0dba)
// Runtime types generated with workerd@1.20250405.0 2025-04-07
declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
  }
}
interface Env extends Cloudflare.Env {}
