// Generated by Wrangler by running `wrangler types` (hash: f79c26f1c03d6ff3a514ac9fa987249a)
// Runtime types generated with workerd@1.20250405.0 2025-04-07
declare namespace Cloudflare {
  interface Env {
    ADMIN_EMAIL: string;
    DB: D1Database;
  }
}
interface Env extends Cloudflare.Env {}
