/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/$graph'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GraphIndexRouteImport } from './routes/$graph.index'
import { Route as GraphStudioRouteImport } from './routes/$graph.studio'
import { Route as GraphUnlockRouteImport } from './routes/$graph_.unlock'
import { Route as OpenGraphIdRouteImport } from './routes/open.$graphId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/$graph',
  path: '/$graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GraphRoute,
} as any)
const GraphStudioRoute = GraphStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => GraphRoute,
} as any)
const GraphUnlockRoute = GraphUnlockRouteImport.update({
  id: '/$graph_/unlock',
  path: '/$graph/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenGraphIdRoute = OpenGraphIdRouteImport.update({
  id: '/open/$graphId',
  path: '/open/$graphId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$graph': typeof GraphRouteWithChildren
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph/studio': typeof GraphStudioRoute
  '/$graph/unlock': typeof GraphUnlockRoute
  '/open/$graphId': typeof OpenGraphIdRoute
  '/$graph/': typeof GraphIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph/studio': typeof GraphStudioRoute
  '/$graph/unlock': typeof GraphUnlockRoute
  '/open/$graphId': typeof OpenGraphIdRoute
  '/$graph': typeof GraphIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$graph': typeof GraphRouteWithChildren
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph/studio': typeof GraphStudioRoute
  '/$graph_/unlock': typeof GraphUnlockRoute
  '/open/$graphId': typeof OpenGraphIdRoute
  '/$graph/': typeof GraphIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$graph'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph/studio'
    | '/$graph/unlock'
    | '/open/$graphId'
    | '/$graph/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph/studio'
    | '/$graph/unlock'
    | '/open/$graphId'
    | '/$graph'
  id:
    | '__root__'
    | '/'
    | '/$graph'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph/studio'
    | '/$graph_/unlock'
    | '/open/$graphId'
    | '/$graph/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRouteWithChildren
  CreateRoute: typeof CreateRoute
  DebugRoute: typeof DebugRoute
  ImportRoute: typeof ImportRoute
  GraphUnlockRoute: typeof GraphUnlockRoute
  OpenGraphIdRoute: typeof OpenGraphIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$graph': {
      id: '/$graph'
      path: '/$graph'
      fullPath: '/$graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$graph/': {
      id: '/$graph/'
      path: '/'
      fullPath: '/$graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof GraphRoute
    }
    '/$graph/studio': {
      id: '/$graph/studio'
      path: '/studio'
      fullPath: '/$graph/studio'
      preLoaderRoute: typeof GraphStudioRouteImport
      parentRoute: typeof GraphRoute
    }
    '/$graph_/unlock': {
      id: '/$graph_/unlock'
      path: '/$graph/unlock'
      fullPath: '/$graph/unlock'
      preLoaderRoute: typeof GraphUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open/$graphId': {
      id: '/open/$graphId'
      path: '/open/$graphId'
      fullPath: '/open/$graphId'
      preLoaderRoute: typeof OpenGraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GraphRouteChildren {
  GraphStudioRoute: typeof GraphStudioRoute
  GraphIndexRoute: typeof GraphIndexRoute
}

const GraphRouteChildren: GraphRouteChildren = {
  GraphStudioRoute: GraphStudioRoute,
  GraphIndexRoute: GraphIndexRoute,
}

const GraphRouteWithChildren = GraphRoute._addFileChildren(GraphRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRouteWithChildren,
  CreateRoute: CreateRoute,
  DebugRoute: DebugRoute,
  ImportRoute: ImportRoute,
  GraphUnlockRoute: GraphUnlockRoute,
  OpenGraphIdRoute: OpenGraphIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
