/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GraphRouteImport } from './routes/$graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphIndexRouteImport } from './routes/$graph.index'
import { Route as GraphUnlockRouteImport } from './routes/$graph_.unlock'
import { Route as GraphNoteNoteRouteImport } from './routes/$graph.note.$note'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/$graph',
  path: '/$graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GraphRoute,
} as any)
const GraphUnlockRoute = GraphUnlockRouteImport.update({
  id: '/$graph_/unlock',
  path: '/$graph/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphNoteNoteRoute = GraphNoteNoteRouteImport.update({
  id: '/note/$note',
  path: '/note/$note',
  getParentRoute: () => GraphRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$graph': typeof GraphRouteWithChildren
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph/unlock': typeof GraphUnlockRoute
  '/$graph/': typeof GraphIndexRoute
  '/$graph/note/$note': typeof GraphNoteNoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph/unlock': typeof GraphUnlockRoute
  '/$graph': typeof GraphIndexRoute
  '/$graph/note/$note': typeof GraphNoteNoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$graph': typeof GraphRouteWithChildren
  '/create': typeof CreateRoute
  '/debug': typeof DebugRoute
  '/import': typeof ImportRoute
  '/$graph_/unlock': typeof GraphUnlockRoute
  '/$graph/': typeof GraphIndexRoute
  '/$graph/note/$note': typeof GraphNoteNoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$graph'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph/unlock'
    | '/$graph/'
    | '/$graph/note/$note'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph/unlock'
    | '/$graph'
    | '/$graph/note/$note'
  id:
    | '__root__'
    | '/'
    | '/$graph'
    | '/create'
    | '/debug'
    | '/import'
    | '/$graph_/unlock'
    | '/$graph/'
    | '/$graph/note/$note'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRouteWithChildren
  CreateRoute: typeof CreateRoute
  DebugRoute: typeof DebugRoute
  ImportRoute: typeof ImportRoute
  GraphUnlockRoute: typeof GraphUnlockRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$graph': {
      id: '/$graph'
      path: '/$graph'
      fullPath: '/$graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$graph/': {
      id: '/$graph/'
      path: '/'
      fullPath: '/$graph/'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof GraphRoute
    }
    '/$graph_/unlock': {
      id: '/$graph_/unlock'
      path: '/$graph/unlock'
      fullPath: '/$graph/unlock'
      preLoaderRoute: typeof GraphUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$graph/note/$note': {
      id: '/$graph/note/$note'
      path: '/note/$note'
      fullPath: '/$graph/note/$note'
      preLoaderRoute: typeof GraphNoteNoteRouteImport
      parentRoute: typeof GraphRoute
    }
  }
}

interface GraphRouteChildren {
  GraphIndexRoute: typeof GraphIndexRoute
  GraphNoteNoteRoute: typeof GraphNoteNoteRoute
}

const GraphRouteChildren: GraphRouteChildren = {
  GraphIndexRoute: GraphIndexRoute,
  GraphNoteNoteRoute: GraphNoteNoteRoute,
}

const GraphRouteWithChildren = GraphRoute._addFileChildren(GraphRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRouteWithChildren,
  CreateRoute: CreateRoute,
  DebugRoute: DebugRoute,
  ImportRoute: ImportRoute,
  GraphUnlockRoute: GraphUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
